### ISSUE TITLE
Assume that start/end values are sub-strings

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/embed-code#15]
Currently `start` and `end` parameters contain `*` at the both ends of an argument most of the time. It would be more convenient to assume that if nothing is mentioned then we assume that the given value is a sub-string that we seek in the lines of the code. To specifically require that the value starts from the given characters, let's use either specific symbols for the start and the end of an expression.

**Comment by dmdashenkov** [comment]
Resolved in #16.
