### ISSUE TITLE
Support regular expressions for fragment selection

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/embed-code#2]
Right now, it is only possible to select code fragments using the `#docfragment` syntax.

We should also allow specifying starting and ending fragment lines via regular expressions.

**Comment by dmdashenkov** [comment]
It was suggested that we use GLOB patterns instead of regex patterns. @alexander-yevsyukov, what's your take on this?

**Comment by alexander-yevsyukov** [comment]
GLOB is easier than regex. Let's use it.

**Comment by dmdashenkov** [comment]
Resolved by #7.
