### ISSUE TITLE
[Go] Joined parts of the same fragment should be trimmed separately

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [SpineEventEngine/embed-code#38]
Looks like the tool trims the resulting fragment. It detects a common minimal indent of all lines and removes it.

So that the following fragment:
```java
        Engine engine = Engine.newInstance(EngineOptions.newBuilder(renderingMode)
                .diskCacheSize(33554432)
                .build());
```

Becomes this:
```java
Engine engine = Engine.newInstance(EngineOptions.newBuilder(renderingMode)
        .diskCacheSize(33554432)
        .build());
```

This rule should not be applied to the composite fragments. In this case, firstly, we would like to trim each "part" separately, and only then join.

Now it looks like this:
```java
import com.teamdev.jxbrowser.view.swing.BrowserView
...
        val view = BrowserView.newInstance(browser)
```

The import has no indent at all. The second sub-fragment resides within a class method (4 + 4 spaces). Their common minimal indent is zero. There's no trimming.

We would like to have this:
```java
import com.teamdev.jxbrowser.view.swing.BrowserView
...
val view = BrowserView.newInstance(browser)
```

### Make it configurable per-fragment?

As for now, I don't see any cases, in which we need this to be configurable.

**Comment by dmytro-kashcheiev** [comment]
I don't think this should be configurable. We should follow one code style consistently across the board. If we trim in one place, we should trim everywhere. Additionally, our current system is already quite complex, and adding more configuration options would only increase this complexity.
