### ISSUE TITLE
[Go] The tool doesn't start

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [SpineEventEngine/embed-code#55]
I can't start the tool no matter how I pass the paths.

Both the config file and the arguments lead to errors:

![image](https://github.com/user-attachments/assets/57bf1e12-79ea-49b7-ae2b-d28586886c87)

The used config file:

```yaml
code-path: "../../JxBrowser-Snippets/src"
docs-path: "../_i18n/en/docs/guides"
```

**Comment by olena-zmiiova** [comment]
The related PR with the fix is merged: https://github.com/SpineEventEngine/embed-code/pull/56
@yevhenii-nadtochii, can you please verify as well?

**Comment by yevhenii-nadtochii** [comment]
Works like a charm, thank you.
